### ISSUE TITLE
Do you have any plans to upgrade project to Java11?

### ISSUE THREAD

**Issue by domik82** [anhldbk/swarm#16]
https://github.com/anhldbk/swarm/blob/7c1f009fb88da0cd911b3c57d59fa3f46c6b1c30/pom.xml#L27

**Comment by anhldbk** [comment]
@domik82 any clear reason to use Java 11? According to [this post](https://www.baeldung.com/java-in-2019), Java 8 occupies 80% market share. And your Swarm-based apps can use Java 11 if you want.

**Comment by anhldbk** [comment]
Close due to inactivity
