### ISSUE TITLE
'num_clients' renamed to 'num_users'

### ISSUE THREAD

**Issue by poznas** [anhldbk/swarm#19]
```
locustio==0.14.6
locust==1.0.2
```
in the latest versions of locust 'num_clients' has been renamed to 'num_users'

`onHatch()` method seems unprepared for that and throws NPE:

![image](https://user-images.githubusercontent.com/23015353/83253985-3f80ab80-a1ae-11ea-9529-b9594d455b42.png)

@myzhan recently fixed it in [locust4j](https://github.com/myzhan/locust4j/commit/7c3572c7ed71522bab6c982cee085d5b2b5eb795)

**Comment by anhldbk** [comment]
@poznas Thank you. This was fixed in [code here](https://github.com/anhldbk/swarm/blob/3c4a869dc9df38db2558c5f412473baee4232d67/src/main/java/com/bigsonata/swarm/Locust.java#L226-L230)
