### ISSUE TITLE
The main thread doesn't terminate if the tests are stopped from the web UI

### ISSUE THREAD

**Issue by priyeshkpandey** [anhldbk/swarm#6]
Version: 0.1.2

I have observed that when we stop our tests from the locust UI by clicking the STOP button, the main java thread doesn't terminate and hangs on. 

Please let me know if this can be achieved in any way or is this a feature that needs to be implemented.

**Comment by anhldbk** [comment]
@priyeshkpandey I'm afraid that does NOT follow Locust protocol. Have a look at this: https://github.com/locustio/locust/blob/master/locust/runners.py#L306-L314
