### ISSUE TITLE
When running in non-UI mode, it doesn't hold the main thread

### ISSUE THREAD

**Issue by priyeshkpandey** [anhldbk/swarm#7]
Swarm Version: 0.1.2
Locust Version: 0.9

When I am running my test in non-UI mode, the main thread doesn't wait until completion of the time duration for the tests and the JVM shuts down hence ending the test.

Please suggest if any other way or is it a new feature to be added?

**Comment by anhldbk** [comment]
I think there's something wrong with your code. Please show me your code.

**Comment by priyeshkpandey** [comment]
@anhldbk I cannot share my code in the current form as it has too much of company related info. I will get demo code done to recreate this. Meanwhile, I have done a workaround to to overcome this.

**Comment by anhldbk** [comment]
Issue's closed due to inactivity
