### ISSUE TITLE
Running multiple crons concurrently

### ISSUE THREAD

**Issue by jagan-autonomic** [anhldbk/swarm#8]
- I am calling locust.register(<list of crons>).
- It seems like all of these crons are getting spawned properly but only one of them ever gets executed throughout the lifecycle of the load test.
- I can see that all the Crons do get initialized and disposed but `process` is called on only one of them.

Is this by design or a bug or am I doing something wrong?

**Comment by jagan-autonomic** [comment]
Never mind.. i was configuring the weights incorrectly.

**Comment by anhldbk** [comment]
@jagan-autonomic You're welcome
